// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiiHWXnJZvtAJCSPX3vukIbM99EdpBDaM',
    appId: '1:1038335340036:web:97e4863d139479ea4a0f51',
    messagingSenderId: '1038335340036',
    projectId: 'chatapp-master-56dd6',
    authDomain: 'chatapp-master-56dd6.firebaseapp.com',
    databaseURL: 'https://chatapp-master-56dd6-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-master-56dd6.appspot.com',
    measurementId: 'G-WW12DNGRDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaaES9eAuRdtSMm7YELCkkhIST8CQzDeM',
    appId: '1:1038335340036:android:fa6578ef527006884a0f51',
    messagingSenderId: '1038335340036',
    projectId: 'chatapp-master-56dd6',
    databaseURL: 'https://chatapp-master-56dd6-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-master-56dd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtmCdLkNNs3cmzIPlRc0e0n3I9DVn28k',
    appId: '1:1038335340036:ios:2a8acc4914ec573b4a0f51',
    messagingSenderId: '1038335340036',
    projectId: 'chatapp-master-56dd6',
    databaseURL: 'https://chatapp-master-56dd6-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-master-56dd6.appspot.com',
    iosClientId: '1038335340036-2or26ru8r13phanspfgokl80gp5bn62f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtmCdLkNNs3cmzIPlRc0e0n3I9DVn28k',
    appId: '1:1038335340036:ios:48dca826ce0720694a0f51',
    messagingSenderId: '1038335340036',
    projectId: 'chatapp-master-56dd6',
    databaseURL: 'https://chatapp-master-56dd6-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-master-56dd6.appspot.com',
    iosClientId: '1038335340036-ksucsidlfer0p0t2p9a866urk43pcfhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappMaster.RunnerTests',
  );
}
